version: '3.1'

services:

  php-fpm:
    build:
      context: ./app
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./app:/app:rw,cached
    environment:
      APP_ENV: dev
      DB_NAME: db
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASS: pass
      DB_DRIVER: pdo_mysql
  nginx:
    build:
      context: ./app
      dockerfile: docker/nginx/Dockerfile
    environment:
      PHP_HOST: php-fpm
    volumes:
      - ./app:/app:rw,cached
    ports:
      - 8000:80
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: '1'